// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggdwxfgrknonpdccijdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnZHd4Zmdya25vbnBkY2NpamR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTkwMzAsImV4cCI6MjA2NDE3NTAzMH0.42eVDhA0iaoIHz0_mWVmDOQy8DjL-WymrBIx49we36s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);